server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/janypet"
    username: root
    password: chuongdo2811@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  # Cau lenh CORS

  #Cau lenh JWT
jwt:
  secret: uHqYj4Pk3mZqKmJ9Y2Ey2K8MdGnM9N9uRPv4RYjUDe4GHZ3xJv1pUlWHez2WUkcFZyrK52xVbbFwCWXEtZxpWg==
  expiration: 86400000  # Token hết hạn sau 24 giờ (ms)
     # Token hết hạn sau 24 giờ (ms)
#VNPAY
vnpay:
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: https://your-domain.com/api/payment/return
  tmnCode: YOUR_VNP_TMN_CODE         # <-- Thay bằng TMN Code thực tế của bạn
  hashSecret: YOUR_VNP_HASH_SECRET   # <-- Thay bằng Hash Secret thực tế của bạn
