server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/janypet"
    username: root
    password: chuongdo2811@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


# Cau lenh CORS

#Cau lenh JWT
